function [Fn]=F_n_interior(u_nmo,u_nmt,u_nmth,u_nmf,Dr_nmo,Dr_nmt,Dp_nmo,Dp_nmt,...
    A,B,D,F,F_theta,R,C1,C2,C3,C4,p,d,k,N_r,N_theta,n) 

Fn_C = op_C(u_nmo,u_nmt,u_nmth,u_nmf,C1,C2,C3,C4,n);

if n==1
    Fn = zeros(size(u_nmo));
end
if n == 2
    Fn=(d*op_Dr(A*Dr_nmo,D,N_theta,d,R)+d*A*op_Partial_r(op_Dr(u_nmo,D,N_theta,d,R),D,N_theta,d)...
        +d*op_D_theta(F*Dp_nmo,N_r,N_theta,p)-d*op_D_theta(B*Dr_nmo,N_r,N_theta,p)...
        +d*F*op_D_theta(Dp_nmo,N_r,N_theta,p)-d*B*op_Partial_r(Dp_nmo,D,N_theta,d)...
        -d*F_theta*Dp_nmo+k^2*Fn_C)/(-d^2);    
end
if n > 2
    Fn=(d*op_Dr(A*Dr_nmo,D,N_theta,d,R)+d*A*op_Partial_r(op_Dr(u_nmo,D,N_theta,d,R),D,N_theta,d)...
        +d*op_D_theta(F*Dp_nmo,N_r,N_theta,p)-d*op_D_theta(B*Dr_nmo,N_r,N_theta,p)...
        +d*F*op_D_theta(Dp_nmo,N_r,N_theta,p)-d*B*op_Partial_r(Dp_nmo,D,N_theta,d)... 
        -d*F_theta*Dp_nmo...%n-1
        +A*op_Partial_r(A*Dr_nmt,D,N_theta,d)+F*op_D_theta(F*Dp_nmt,N_r,N_theta,p)...
        -F*op_D_theta(B*Dr_nmt,N_r,N_theta,p)-B*op_Partial_r(F*Dp_nmt,D,N_theta,d)...
        +B*op_Partial_r(B*Dr_nmt,D,N_theta,d)-F*F_theta*Dp_nmt...
        +F_theta*B*Dr_nmt... %n-2
        +k^2*Fn_C )/(-d^2);
end

end